enhancer: removed country from records
SCOAP3/workflows pull request #152
Opened 2023-07-17 12:49 UTC by ErnestaP

* Removed country from records with affiliation value with: cooperation agreement with cern.
* ref: https://github.com/cern-sis/issues-scoap3/issues/176

2023-07-18 09:18 UTC, drjova commented on dags/common/enhancer.py
> +                    r"cooperation agreement with cern", re.IGNORECASE
if we have the `compile` inside the loops it's loosing its advantage over the simple `match`, especially in a double for loop.

2023-07-18 09:19 UTC, drjova requested changes
Thank you 😃 , there is a comment that we have to address.

2023-07-18 09:21 UTC, drjova commented on tests/units/common/test_enhancer.py
> +                    "value": "International laboratory covered by a cooperation agreement with CERN, Geneva, Switzerland",
we are not testing the case that `country` already populated from the XML files.

2023-07-18 15:12 UTC, drjova commented on dags/common/enhancer.py
> +                    r"cooperation agreement with cern", re.IGNORECASE
@ErnestaP ☝️

2023-07-19 06:54 UTC, drjova approved these changes

2023-07-19 06:58 UTC, drjova commented
@ErnestaP could you please squash?

2023-07-19 09:35 UTC, drjova commented
@ErnestaP why there is a merge coomit?

2023-07-19 09:37 UTC, ErnestaP commented
Meger commit because of resolving the merge conflict by using UI

2023-07-19 09:51 UTC, merged