just for test
SCOAP3/workflows pull request #158
Opened 2023-07-27 16:04 UTC by ErnestaP

2023-08-04 10:18 UTC, pamfilos requested changes
please squash commits in the end

2023-08-04 10:18 UTC, pamfilos commented on harvester_docs.md
> +<table>
please update tables with the markdown syntax ( | --- | ----| ) for better compatibility.. lets keep the html tags to as minimal as possible

2023-08-04 10:18 UTC, pamfilos commented on springer_fields_mapping.md
> +| <p id="69">[69]</p> | arxiv_eprints | <a href="_get_arxiv_eprints">_get_arxiv_eprints</a> |
change `<p>` tag to `<a>`..e.g `<p id="68">[68]</p>` => `<a href="#68" id="68">[68]</a>`..this way you can also share by a click-able link

2023-08-07 08:26 UTC, drjova commented on aps_fields_mapping.md
> +<table>
Thanks @ErnestaP, could we change the table from html to markdown?

2023-08-10 13:14 UTC, drjova commented on aps_fields_mapping.md
> +<table>
@ErnestaP the table is still HTML :)

2023-08-16 14:11 UTC, drjova commented
@ErnestaP Thanks. There is a typo `dicumentation`

2023-08-17 07:59 UTC, drjova commented
@ErnestaP could you please squash the commits?

2023-08-22 13:58 UTC, merged